# -*- coding: utf-8 -*-
LANG = {
    "pl": {
        "title": "IPTV Dream v2.1",
        "load_url": "Wczytaj listę z URL",
        "pick_file": "Wskaż plik M3U",
        "xtream": "Xtream Codes",
        "mac_json": "MAC Portal / wklej JSON",
        "own_links": "Własne linki M3U",
        "toggle_lang": "PL / EN",
        "check_upd": "Sprawdź aktualizacje",
        "auto_up": "Auto-aktualizacja",
        "export": "Eksport do bukietu",
        "exit": "Wyjście",
        "yes": "Tak",
        "no": "Nie",
        "update_ok": "Zaktualizowano – restart GUI?",
        "update_fail": "Błąd aktualizacji",
        "no_update": "Masz najnowszą wersję",
        "lang_changed": "Język zmieniono na",
        "loaded": "Wczytano %d kanałów – NIEBIESKI=eksport",
        "load_first": "Najpierw wczytaj listę (1-6)",
        "exported": "Bukiety wyeksportowane – sprawdź TV",
        "auto_off": "Auto-aktualizacja WYŁ.",
        "auto_on": "Auto-aktualizacja WŁ. (05:00)",
        "remote_ver": "Dostępna wersja",
        "local_ver": "Lokalna wersja",
        "update_ask": "Czy chcesz zaktualizować?",
        "press_1_6": "Naciśnij 1-6 aby wybrać źródło",
        "foot": "IPTV Dream v2.1 | msisystem@t.pl | GitHub: OliOli2013"
    },
    "en": {
        "title": "IPTV Dream v2.1",
        "load_url": "Load M3U from URL",
        "pick_file": "Pick M3U file",
        "xtream": "Xtream Codes",
        "mac_json": "MAC Portal / paste JSON",
        "own_links": "Own M3U links",
        "toggle_lang": "PL / EN",
        "check_upd": "Check for updates",
        "auto_up": "Auto-update",
        "export": "Export bouquet",
        "exit": "Exit",
        "yes": "Yes",
        "no": "No",
        "update_ok": "Updated – restart GUI?",
        "update_fail": "Update error",
        "no_update": "You have the latest version",
        "lang_changed": "Language switched to",
        "loaded": "Loaded %d channels – BLUE=export",
        "load_first": "Load list first (1-6)",
        "exported": "Bouquets exported – check TV",
        "auto_off": "Auto-update OFF",
        "auto_on": "Auto-update ON (05:00)",
        "remote_ver": "Available version",
        "local_ver": "Local version",
        "update_ask": "Do you want to update?",
        "press_1_6": "Press 1-6 to choose source",
        "foot": "IPTV Dream v2.1 | msisystem@t.pl | GitHub: OliOli2013"
    }
}
def _(key, lang="pl"):
    return LANG.get(lang, LANG["pl"]).get(key, key)
