# -*- coding: utf-8 -*-
LANG = {
    "pl": {
        "title": "IPTV Dream v5.0",
        "load_url": "Wczytaj listę z URL",
        "pick_file": "Wskaż plik M3U",
        "xtream": "Xtream Codes",
        "mac_json": "MAC Portal (Lista)",
        "own_links": "Własne linki M3U",
        "toggle_lang": "PL / EN",
        "check_upd": "Sprawdź aktualizacje",
        "epg_install": "Instaluj źródła EPG",
        "url_epg": "Własny URL EPG",
        "epg_dream_sources": "IPTV Dream EPG (MEGA)",
        "epg_custom": "Własne EPG (URL)",
        "epg_updated": "Źródła EPG zaktualizowane.",
        "filelist_help": "▲/▼=nawigacja | OK=wybór/wejdź | EXIT=wstecz",
        "auto_up": "Auto-aktualizacja",
        "export": "Eksport do bukietu",
        "exit": "Wyjście",
        "yes": "Tak",
        "no": "Nie",
        "update_ok": "Zaktualizowano – restart GUI?",
        "update_fail": "Błąd aktualizacji",
        "no_update": "Masz najnowszą wersję",
        "lang_changed": "Język zmieniono na",
        "loaded": "Wczytano %d kanałów",
        "load_first": "Najpierw wczytaj listę (1-7)",
        "exported": "Bukiety wyeksportowane.",
        "exported_channels_bouquets": "Wyeksportowano %d kanałów w %d bukietach.",
        "auto_off": "Auto-aktualizacja WYŁ.",
        "auto_on": "Auto-aktualizacja WŁ. (05:00)",
        "remote_ver": "Dostępna wersja",
        "local_ver": "Lokalna wersja",
        "update_ask": "Czy chcesz zaktualizować?",
        "press_1_6": "Naciśnij 1-7 aby wybrać źródło",
        "downloading": "Pobieranie listy... Proszę czekać.",
        "error": "Błąd",
        "foot": "Twórca: Paweł Pawełek, {date} | msisystem@t.pl", 
        "epg_url_saved_info": "Adres URL EPG został zapisany. Naciśnij ŻÓŁTY, aby zainstalować źródła.",
        "epg_install_success_info": "Teraz wejdź w EPG Import -> Źródła i zaznacz 'IPTV Dream EPG (MEGA)'.",
        "download_error": "Błąd pobierania!",
        "downloading_xtream": "Pobieranie Xtream... Proszę czekać.",
        "xtream_error": "Błąd Xtream",
        "downloading_mac": "Pobieranie danych MAC... Proszę czekać.",
        "mac_no_host_mac": "Brak HOST lub MAC w JSON",
        "mac_error": "Błąd MAC",
        "empty_channel_list": "Błąd: Pusta lista kanałów",
        "portal_returned_zero": "Portal zwrócił 0 kanałów.",
        "pick_link": "Wybierz link",
        "no_saved_links": "Brak zapisanych linków.",
        "epg_generating": "Generowanie danych EPG w tle...",
        "epg_done_opening": "Gotowe. Otwieram wybór bukietów...",
        "checking_update": "Szukam aktualizacji...",
        "update_check_error": "Błąd sprawdzania wersji.",
        "update_check_fail_msg": "Nie udało się sprawdzić wersji.",
        "changes": "ZMIANY",
        "no_update_msg": "Masz najnowszą wersję",
        "update_ok_restart_msg": "Wymagany restart GUI. Restartować teraz?",
        "auto_on_full": "Automatyczna aktualizacja została WŁĄCZONA.\nBędzie sprawdzana przy każdym uruchomieniu wtyczki.",
        "auto_off_full": "Automatyczna aktualizacja została WYŁĄCZONA.",
        "xtream_title": "Xtream Codes – nawigacja",
        "cancel": "Anuluj",
        "save": "Zapisz",
        "xtream_help": "↑/↓ – zmiana pola, OK – klawiatura, Zielony – zapisz",
        "enter": "Wpisz",
        "xtream_fill_host_user": "Uzupełnij host i user!",
        "err_404": "Nie znaleziono portalu (Błąd 404).\nSprawdź czy adres URL jest poprawny.",
        "err_401": "Odmowa dostępu (Błąd 401/403).\nTwój MAC może być zablokowany lub wygasł.",
        "err_server": "Błąd serwera dostawcy",
        "try_later": "Spróbuj później.",
        "err_timeout": "Serwer nie odpowiada (Timeout/Brak połączenia).\nSpróbuj ponownie za chwilę.",
        "err_generic": "Błąd połączenia",
        "press_ok_to_edit": "Naciśnij OK, aby edytować.",
        "picker_sum": "Wybierz grupy do eksportu",
        "picker_sum_text": "Wybrano: %d grup, %d kanałów",
        "picker_help": "STRZAŁKI: Nawigacja | OK/ZIELONY: Zaznacz | NIEBIESKI: Eksportuj | LEWO/PRAWO: Zmień listę",
        "picker_search": "Szukaj grupy (wpisz frazę):", # NOWE
        "webif_status": "Web Interfejs (port 9999)",
        "webif_off": "Wyłączony. Wciśnij 8, aby włączyć.",
        "webif_started": "Web Interfejs WŁĄCZONY.",
        "webif_stopped": "Web Interfejs WYŁĄCZONY.",
        "webif_submit": "Wyślij do dekodera",
        "webif_warning": "Uwaga: Dekoder musi mieć otwartą wtyczkę IPTV Dream.",
        "webif_received": "Otrzymano dane z WebIF",
        "support_text_long": "Podoba Ci się wtyczka? Wesprzyj twórcę i rozwój wtyczki.\nDziękuję!",
        
        # PLAYER
        "player_type": "Typ serwisu (Player)",
        "gst_player": "GStreamer (4097)",
        "exte_player": "ExtePlayer3 (5002)",

        # V5.0
        "Dodaj nowy...": "Dodaj nowy...",
        "mac_select_title": "Wybierz Portal MAC",
        "mac_added_info": "Nowy Portal MAC dodany!\nWejdź w opcję 4, aby wybrać.",
        
        "xt_select_type": "Co chcesz pobrać?",
        "xt_live": "Telewizja na żywo (LIVE)",
        "xt_vod": "Filmy i Seriale (VOD)",
        "xt_all": "Wszystko (LIVE + VOD)",
    },
    "en": {
        "title": "IPTV Dream v5.0",
        "load_url": "Load M3U from URL",
        "pick_file": "Pick M3U file",
        "xtream": "Xtream Codes",
        "mac_json": "MAC Portal (List)",
        "own_links": "Own M3U links",
        "toggle_lang": "PL / EN",
        "check_upd": "Check for updates",
        "epg_install": "Install EPG sources",
        "url_epg": "Custom EPG URL",
        "epg_dream_sources": "IPTV Dream EPG (MEGA)",
        "epg_custom": "Custom EPG (URL)",
        "epg_updated": "EPG sources updated.",
        "filelist_help": "▲/▼=navigate | OK=select/enter | EXIT=back",
        "auto_up": "Auto-update",
        "export": "Export bouquet",
        "exit": "Exit",
        "yes": "Yes",
        "no": "No",
        "update_ok": "Updated – restart GUI?",
        "update_fail": "Update error",
        "no_update": "You have the latest version",
        "lang_changed": "Language switched to",
        "loaded": "Loaded %d channels",
        "load_first": "Load list first (1-7)",
        "exported": "Bouquets exported.",
        "exported_channels_bouquets": "Exported %d channels in %d bouquets.",
        "auto_off": "Auto-update OFF",
        "auto_on": "Auto-update ON (05:00)",
        "remote_ver": "Available version",
        "local_ver": "Local version",
        "update_ask": "Do you want to update?",
        "press_1_6": "Press 1-7 to choose source",
        "downloading": "Downloading list... Please wait.",
        "error": "Error",
        "foot": "Creator: Paweł Pawełek, {date} | msisystem@t.pl",
        "epg_url_saved_info": "EPG URL saved. Press YELLOW to install sources.",
        "epg_install_success_info": "Now go to EPG Import -> Sources and select 'IPTV Dream EPG (MEGA)'.",
        "download_error": "Download error!",
        "downloading_xtream": "Downloading Xtream... Please wait.",
        "xtream_error": "Xtream Error",
        "downloading_mac": "Downloading MAC data... Please wait.",
        "mac_no_host_mac": "No HOST or MAC in JSON",
        "mac_error": "MAC Error",
        "empty_channel_list": "Error: Empty channel list",
        "portal_returned_zero": "Portal returned 0 channels.",
        "pick_link": "Pick link",
        "no_saved_links": "No saved links.",
        "epg_generating": "Generating EPG data in background...",
        "epg_done_opening": "Done. Opening bouquet selection...",
        "checking_update": "Checking for updates...",
        "update_check_error": "Version check error.",
        "update_check_fail_msg": "Failed to check version.",
        "changes": "CHANGES",
        "no_update_msg": "You have the latest version",
        "update_ok_restart_msg": "GUI Restart required. Restart now?",
        "auto_on_full": "Auto-update has been ENABLED.\nIt will check on every plugin start.",
        "auto_off_full": "Auto-update has been DISABLED.",
        "xtream_title": "Xtream Codes – navigation",
        "cancel": "Cancel",
        "save": "Save",
        "xtream_help": "↑/↓ – change field, OK – keyboard, Green – save",
        "enter": "Enter",
        "xtream_fill_host_user": "Fill host and user!",
        "err_404": "Portal not found (Error 404).\nCheck if URL is correct.",
        "err_401": "Access denied (Error 401/403).\nYour MAC might be blocked or expired.",
        "err_server": "Provider server error",
        "try_later": "Try again later.",
        "err_timeout": "Server not responding (Timeout/No connection).\nTry again in a moment.",
        "err_generic": "Connection error",
        "press_ok_to_edit": "Press OK to edit.",
        "picker_sum": "Select groups to export",
        "picker_sum_text": "Selected: %d groups, %d channels",
        "picker_help": "ARROWS: Navigate | OK/GREEN: Select | BLUE: Export | LEFT/RIGHT: Switch List",
        "picker_search": "Search group (enter text):",
        "webif_status": "Web Interface (port 9999)",
        "webif_off": "Off. Press 8 to turn on.",
        "webif_started": "Web Interface ON.",
        "webif_stopped": "Web Interface OFF.",
        "webif_submit": "Send to Receiver",
        "webif_warning": "Note: The IPTV Dream plugin must be open on the receiver.",
        "webif_received": "Received data from WebIF",
        "downloading_mac": "MAC Auth & Downloading...",
        "support_text_long": "Do you like the plugin? Support the creator and development.\nThank you!",
        
        # PLAYER
        "player_type": "Service Type (Player)",
        "gst_player": "GStreamer (4097)",
        "exte_player": "ExtePlayer3 (5002)",

        # V5.0
        "Dodaj nowy...": "Add new...",
        "mac_select_title": "Select MAC Portal",
        "mac_added_info": "New MAC Portal added!\nSelect Option 4 to choose.",
        
        "xt_select_type": "Select content to download:",
        "xt_live": "Live TV Only",
        "xt_vod": "Movies & Series (VOD)",
        "xt_all": "Everything (Live + VOD)",
    }
}
def _(key, lang="pl"):
    return LANG.get(lang, LANG["pl"]).get(key, key)
